### ISSUE TITLE
Need a way to print RISE slides to pdf

### ISSUE THREAD

**Issue by kbenoit** [lse-st445/lectures#1]
one slide per page

Is addressed here: https://github.com/damianavila/RISE/issues/127

Using [Decktape](https://github.com/astefanutti/decktape) but @milenavt did not get it working very well - said the slides messed up the text.

**Comment by chmue** [comment]
```sh
jupyter-nbconvert --to slides --SlidesExporter.reveal_url_prefix='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0/' ST445_wk1_admin.ipynb
[NbConvertApp] Converting notebook ST445_wk1_admin.ipynb to slides
[NbConvertApp] Writing 260252 bytes to ST445_wk1_admin.slides.html
```

Then opening `ST445_wk1_admin.slides.html` in Chrome/Chromium printing to file generates this PDF: [ST445_wk1_admin slides.pdf](https://github.com/lse-st445/lectures/files/1317998/ST445_wk1_admin.slides.pdf)

**Comment by milenavt** [comment]
@chmue I tried doing this but it works pretty badly when there are images and code in the slides - it gets garbled up and overlaid.

**Comment by chmue** [comment]
Ah, ok @milenavt.

I tried it with the slides for classes which contain some code on slide 8. It looks ok to me... What do you think?

[ST445_wk1_class slides.pdf](https://github.com/lse-st445/lectures/files/1318078/ST445_wk1_class.slides.pdf)

**Comment by milenavt** [comment]
@chmue Hm. so perhaps the issue is with images or with my setup. Can you try this one please: https://github.com/lse-my470/lectures/blob/master/wk2/MY470_wk2_lecture.ipynb

**Comment by kbenoit** [comment]
@chmue Awesome! I'm not worried about the very minor alignment issue!

**Comment by chmue** [comment]
Here you go @milenavt: [MY470_wk2_lecture slides.pdf](https://github.com/lse-st445/lectures/files/1318187/MY470_wk2_lecture.slides.pdf)

Are you using `?print-pdf` when opening the file locally? E.g. this is the URL line for your slides when I print them: `file:///home/cmueller/academia/cur/teaching/MY470-lectures/wk2/MY470_wk2_lecture.slides.html?print-pdf#/`

```
wk2 [master●] % chromium --version
Chromium 61.0.3163.91
```

**Comment by milenavt** [comment]
@chmue  @kbenoit  Great, problem solved! I now just need to figure out why it did not work on my computer...

**Comment by kbenoit** [comment]
@chmue This worked perfectly last week, but does not seem to be working now. Any ideas?

**Comment by chmue** [comment]
I'm looking into this. I'll also give `decktape` a try but I think that the resulting pages should be the same as when using the Chrome/Chromium normally as it uses a headless version of Chrome.

**Comment by chmue** [comment]
It seems that the slides this week hit multiple issues both with markdown and reveal.js (and HTML presentation frameworks in general):

- The big markdown *problem* of no clearly defined syntax 😒 (the link does not even work on GitHub, i.e. the markdown engine that GH uses cannot parse this correctly):
  `http://johnmacfarlane.net/babelmark2/?text=%5Blink%5D(abc%5C))`
- reveal.js does not *really* support printing. It has some helpers but if you want anything non-default  you're more or less on your own.
    - We seem to run into an issue with content that is too big for one slide so basically rolls over to the next. The PDF produces a second slide but the content does not roll over.

I have fixed some of the markdown issues with links through trial and error.
I have also played around with Firefox and Chromium to make the printing work but no success so far.
I am still in the process of making `decktape` work for me.

**Comment by chmue** [comment]
So after more fiddling around yesterday:

- You can include links with parentheses in the [particular flavour of markdown that jupyter uses](https://github.com/lepture/mistune) with [the following syntax](http://pandoc.org/MANUAL.html#reference-links). [CommonMark ways of handling parentheses](http://spec.commonmark.org/0.28/#links), e.g. `\(` or wrapping in `<>`, do not work.

    ```
   This is a [Link to content]
   This is other content

    [Link to content]: https://example.com/(abc)
    ```
- TBD: Will update soon but need to go to an event now
- `decktape` does not work on my standards-compliant Linux flavour because it relies on a non-standard kernel compilation flag. It will probably work on most other Linux flavours (e.g. Debian, Ubuntu) and probably also on Win, Mac though.
