### ISSUE TITLE
Extracting data from dfm (Quanteda package)

### ISSUE THREAD

**Issue by sidrajgopalan** [lse-st445/lectures#11]
For assignment 5, I extracted the positive and negative sentiments and it is stored as a document feature matrix. What is the best non-manual way of extracting the aggregate positive and negative words by device into a data frame so it can be plotted using ggplot?

Is it by extracting the x vector?

**Comment by kbenoit** [comment]
Probably `t(as.data.frame(your_sentiment_dfm))`

**Comment by kbenoit** [comment]
or `t(as.data.frame(as.matrix(your_sentiment_dfm)))`
