### ISSUE TITLE
Cosine similarity matrix

### ISSUE THREAD

**Issue by sidrajgopalan** [lse-st445/lectures#13]
I have a question regarding assignment 8 part B.2: "Do the same but for the cosine similarity of pairs of programming languages with respect to their co-usage in GitHub repositories."

Does this essentially mean we use the cosine_similarity function and pass our input matrix (co-usage pairs) and then re-do the 3 heatmaps based on the output of the cosine similarity function?

I am currently using this code: 
similarities = cosine_similarity(pair_mx) 
where pair_mx is my original co-usage matrix and then I do the heatmaps on the similarities matrix

Please correct me if I am misinterpreting the question

**Comment by sidrajgopalan** [comment]
@christineyuen @milanvojnovic would be great to get your input before the deadline. Apologies for the bringing up the question closer to the deadline.

**Comment by christineyuen** [comment]
Yes
