### ISSUE TITLE
Use a separate repository for the main course website

### ISSUE THREAD

**Issue by kbenoit** [lse-st445/lectures#2]
Would it make more sense to have a `lse-st445.github.io` repository, for the course handout, and use the `lectures` repository for lectures only?

**Comment by chmue** [comment]
I think a separate website with static, evaluated versions of the ipython notebooks as well as PDFs would make sense. It would basically be a nicely presented version of the content in this repo. Eventually, we could setup continuous integration to automatically recompile notebooks and PDFs and push them to the website 🙂

**Comment by kbenoit** [comment]
I just set up https://lse-st445.github.io, which contains the `lectures/README.md` but as `index.md`. Of course it could be fancier, but it works for now and does not have all of the GitHub junk before the content.

@milanvojnovic This would allow us complete control over the lectures repository, in terms of not just access but also archiving years. Meaning: We could make it private, and rename it to `lectures-MT2017` so that future versions of the course would get new repositories.

**Comment by chmue** [comment]
I can look into integrating the lecture content. I made [this simple site](https://chmue.github.io/my457-2016/) for notes in the MSc.

**Comment by kbenoit** [comment]
Very nice. Milena and I are mostly using Jupyter notebooks for the lecture notes, however, and that [already supports MathJax](http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Working%20With%20Markdown%20Cells.html#LaTeX-equations). And @milanvojnovic will use Powerpoint. 

We would be linking the pages in the `lectures` repo to the handout `index.md`, e.g. links to pages such as https://github.com/lse-my470/lectures/blob/master/wk1/MY470_wk1_lecture.ipynb (although for ST445, obviously - it's just that @milenavt is ahead of me in the lecture notes dept...). 

For all else, happy to use simple GitHub flavoured markdown for now.

**Comment by chmue** [comment]
Ok, so you want to link directly to the pages in the repo with the actual content?

**Comment by kbenoit** [comment]
Yes I was thinking to add links in `lse-st445.github.io` to the `lectures/day1/day1lecture.ipynb`, `lectures/day1/day1lecture.pdf, etc.
