### ISSUE TITLE
Finalize assignment 1

### ISSUE THREAD

**Issue by kbenoit** [lse-st445/lectures#6]
Merge the `.ipynb` and `.md` files currently in `week01/`, into a mixture of instructions and slides, for reviewing git and GitHub in class. Might be better to use ipynb?

Figure out:
- [x] whether we should use GitHub classroom for this assignment, and how - worth asking @milenavt 
- [x] How (and whether we need) to solicit their GitHub user names before we can use GitHub classroom

**Comment by christineyuen** [comment]
1. I think we should if we are going to use it for future assignments? The videos I found on their website are quite useful: [https://classroom.github.com/videos](https://classroom.github.com/videos). I can try to setup the assignment, if you want
2. No, they can access the assignment as long as they have the link to the assignment. For example, you can click this: [https://classroom.github.com/a/LiNWFTUR](https://classroom.github.com/a/LiNWFTUR) to access an assignment of ST446.

**Comment by kbenoit** [comment]
OK let’s use it. Can you create the assignment, and test it out? I’ll be happy to edit it once you notify me it’s ready. You can use what I already did, just make it a bit more specific. Thanks!

**Comment by milenavt** [comment]
@christineyuen Indeed, the tutorial is quite clear and the process is relatively straightforward. My only advice would be to ask the students to push (commit to master) directly rather than issue a pull request. There is no need for pull requests really.

**Comment by christineyuen** [comment]
I think I can set the classroom assignment but there are 2 issues: 

1. Each student and assignment will have their own repository under root like /assignment-i-student-j. This means later we will have n*k new repositories under root (n is number of students and k assignments), which makes it quite difficult to manage and navigate the whole course github page. I thought I could set the home repository/folder for each assignment to make it like /assignment/assignment-i/student-j but seems it is not the case. Please see the section "too many Too many repos" under [https://theforeverstudent.com/review-github-classroom-80c8d0c4081a](https://theforeverstudent.com/review-github-classroom-80c8d0c4081a) and this [https://github.com/education/classroom/issues/534](https://github.com/education/classroom/issues/534)

2. Similarly, when we assign the instructions or the starting code to an assignment, these codes have to be in a repository as well. This means we will have k more repositories just for instructions.

I think the whole thing still works, I just want to let you know about this before the flooding of repositories...

**Comment by milenavt** [comment]
Yes, this is quite unfortunate but I don't think there is currently a way around it. At least the assignments are better organized in the classroom, so it will be easier to check submissions there.

**Comment by christineyuen** [comment]
1. I have created a simple assignment in GitHub Classroom. I did not move the fixing R file part to here because students can just update and commit their work without going through the workflow procedure like pulling requests (as mentioned by @milenavt), but i suppose the main purpose of the fixing R file section is for them to practice the workflow.
2. I have tested the assignment by submitting my own answer. You can see my submission here: [https://github.com/lse-st445/assignment-1-christineyuen/blob/master/information.md](https://github.com/lse-st445/assignment-1-christineyuen/blob/master/information.md)
3. I have also roughly updated the corresponding class documents to include this part of the assignment.

Thank you.
